"""
PDF export

Renders already-markdown-rendered HTML (the same content_html/study_html
each result page already produces) into a downloadable PDF via xhtml2pdf -
a pure-Python HTML-to-PDF library with no system-level dependencies (unlike
WeasyPrint's Cairo/Pango requirement), so it's safe to add without touching
the Railway build config.

xhtml2pdf supports only a modest CSS subset (no flexbox/grid, no CSS custom
properties) - this uses a dedicated, hardcoded print stylesheet rather than
reusing styles.css.
"""

import re
from html import escape
from io import BytesIO

from xhtml2pdf import pisa

_STYLE = """
<style>
    @page {
        size: letter;
        margin: 2.2cm 2cm;
    }
    body {
        font-family: Georgia, "Times New Roman", serif;
        font-size: 11pt;
        line-height: 1.5;
        color: #1a1612;
    }
    h1 {
        font-size: 20pt;
        color: #1a1612;
        border-bottom: 2pt solid #b8860b;
        padding-bottom: 6pt;
        margin-bottom: 4pt;
    }
    .meta-line {
        font-size: 9pt;
        color: #6b5d4d;
        margin-bottom: 18pt;
    }
    h2 {
        font-size: 15pt;
        color: #6b2d5b;
        margin-top: 20pt;
    }
    h3 {
        font-size: 13pt;
        color: #1a1612;
        margin-top: 14pt;
    }
    a {
        color: #6b2d5b;
    }
    blockquote {
        margin: 10pt 0 10pt 0;
        padding: 6pt 12pt;
        border-left: 3pt solid #b8860b;
        color: #3d342a;
        font-style: italic;
    }
    strong { color: #1a1612; }
    .footer-note {
        margin-top: 24pt;
        font-size: 8pt;
        color: #6b5d4d;
        border-top: 0.5pt solid #cccccc;
        padding-top: 8pt;
    }
</style>
"""


def slugify(text: str, max_length: int = 60) -> str:
    """Filesystem/URL-safe slug for a PDF download filename."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_length].strip("-") or "document"


def render_pdf(title: str, meta_line: str, content_html: str, source_url: str = "") -> bytes:
    """
    Render rendered content HTML into a PDF.

    Args:
        title: Document title (e.g. the reference, or analysis headline)
        meta_line: Small subtitle line (engine/date/word count, etc.)
        content_html: Already-rendered HTML body (same content_html/study_html
            each result page passes to its template - markdown already
            converted, scripture links already applied)
        source_url: Optional canonical URL to print in the footer

    Returns:
        PDF file bytes

    Raises:
        Exception: If PDF generation fails
    """
    footer = '<div class="footer-note">Generated by The Lectionary Engines'
    if source_url:
        footer += f" — {escape(source_url)}"
    footer += "</div>"

    full_html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8">{_STYLE}</head>
<body>
    <h1>{escape(title)}</h1>
    <div class="meta-line">{escape(meta_line)}</div>
    {content_html}
    {footer}
</body>
</html>"""

    buffer = BytesIO()
    result = pisa.CreatePDF(full_html, dest=buffer)
    if result.err:
        raise Exception(f"PDF generation failed with {result.err} error(s)")
    return buffer.getvalue()
